apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: pstkc3blb-python 
  janus-idp.io/tekton: pstkc3blb-python
  backstage.io/kubernetes-id: pstkc3blb-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: pstkc3blb-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml