apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pstkc3blb-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pstkc3blb-python 
  name: pstkc3blb-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pstkc3blb-python 
